server:
  port: ${PORT:8081}

spring:
  datasource:
    url: jdbc:postgresql://${FIREVOX_DB_IP:localhost}:${FIREVOX_DB_PORT:5432}/firevox?ApplicationName=${spring.application.name}
    username: ${FIREVOX_DB_USERNAME:firevox}
    password: ${FIREVOX_DB_PASSWORD:firevox}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET TIME ZONE 'Etc/UTC'
      schema: firevox
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:firevox}
    password: ${RABBIT_PASSWORD:firevox}
    ssl:
      enabled: ${RABBIT_SSL:false}
    listener:
      simple:
        acknowledge-mode: manual
  cloud:
    stream:
      bindings:
        voxels-in-0:
          destination: voxels-process
          content-type: application/json
          group: voxels-process
        radiation-in-0:
          destination: radiation-process
          content-type: application/json
          group: radiation-process

logging:
  level:
    org:
      springframework:
        security: INFO
      keycloak:
        adapters: INFO
      hibernate:
        SQL: INFO

firevox:
  maxSize: ${FIREVOX_MAX_DIMENSION:20000}
  timestep: 0.1
  smokeIntoFireThreshold: 200.0
  voxel:
    size: ${VOXEL_SIZE:0.01} # in meters