apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
spec:
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: europe-central2-docker.pkg.dev/firevox/firevox-repository/scheduler
          ports:
            - containerPort: 8083
          env:
            - name: PORT
              value: "8083"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/app/auth.json"
            - name: Voxel_SERVICE_ADDR
              value: "http://Voxel:8080"
            - name: CURRENCY_SERVICE_ADDR
              value: "http://currency:8081"
            - name: NOTIFICATION_SERVICE_ADDR
              value: "http://notification:8082"
            - name: PAYMENT_SERVICE_ADDR
              value: "http://payment:8084"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "http://product-catalog:8085"
            - name: SHIPPING_SERVICE_ADDR
              value: "http://shipment:8086"
          resources:
            requests:
              cpu: 1000m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 60
            failureThreshold: 10
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 60
            failureThreshold: 10
            periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: scheduler
spec:
  type: LoadBalancer
  selector:
    app: scheduler
  ports:
    - name: scheduler-api-port
      port: 8083
      targetPort: 8083