apiVersion: apps/v1
kind: Deployment
metadata:
  name: Voxel
spec:
  selector:
    matchLabels:
      app: Voxel
  template:
    metadata:
      labels:
        app: Voxel
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: europe-central2-docker.pkg.dev/firevox/firevox-repository/Voxel
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_ADDRESS
              value: "10.23.139.219"
            - name: PORT
              value: "8080"
          resources:
            requests:
              cpu: 1000m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 3
            initialDelaySeconds: 60
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 3
            initialDelaySeconds: 60
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: Voxel
spec:
  type: LoadBalancer
  selector:
    app: Voxel
  ports:
    - name: Voxel-api-port
      port: 8080
      targetPort: 8080