apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: worker
build:
  artifacts:
  - image: firevox/worker
    context: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - ./kubernetes/worker.yaml
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
- name: dockerfile
  build:
    artifacts:
    - image: firevox/worker
      context: .
