server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:postgresql://${FIREVOX_DB_IP:localhost}:${FIREVOX_DB_PORT:5432}/firevox?ApplicationName=${spring.application.name}
    username: ${FIREVOX_DB_USERNAME:firevox}
    password: ${FIREVOX_DB_PASSWORD:firevox}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET TIME ZONE 'Etc/UTC'
      schema: firevox
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:firevox}
    password: ${RABBIT_PASSWORD:firevox}
    ssl:
      enabled: ${RABBIT_SSL:false}
    listener:
      simple:
        acknowledge-mode: manual
  cloud:
    stream:
      bindings:
        voxels-out-0:
          destination: voxels-process
          content-type: application/json
          group: voxels-process
        radiation-out-0:
          destination: radiation-process
          content-type: application/json
          group: radiation-process
        radiation-start-out-0:
          destination: radiation-start
          content-type: application/json
          group: radiation-start
        radiation-start-in-0:
          destination: radiation-start
          content-type: application/json
          group: radiation-start
        simulation-start-in-0:
          destination: simulation-start
          content-type: application/json
          group: simulation-start
        simulation-start-out-0:
          destination: simulation-start
          content-type: application/json
          group: simulation-start

logging:
  level:
    org:
      springframework:
        security: INFO
      keycloak:
        adapters: INFO
      hibernate:
        SQL: INFO

firevox:
  maxSize: ${FIREVOX_MAX_DIMENSION:20000}
  simulation:
    files:
      path: ${FIREVOX_SIMULATION_FILES_PATH:"simulation/files"}
  synchronisation:
    time: 1000

